framework:
    messenger:
        default_bus: query.bus
        buses:
            query.bus:
                middleware:
                    - validation

            command.bus:
                middleware:
                    - validation
                    - doctrine_transaction

            event.bus:
                default_middleware: allow_no_handlers
                middleware:
                    - validation
                    - doctrine_transaction

        transports:
            async:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%)'
                #serializer: messenger.transport.symfony_serializer
                retry_strategy:
                    max_retries: 0
                    delay: 1000
                options:
                    exchange:
                        name: messages
                        type: direct
                        default_publish_routing_key: normal
                    queues:
                        auctions.domain.bid_created:
                            binding_keys: [auctions.domain.bid_created]
                        auctions.domain.auction_closed:
                            binding_keys: [auctions.domain.auction_closed]
            sync: 'sync://'

        routing:
            'App\Shared\Domain\Bus\Event\DomainEvent': async

# when@test:
#    framework:
#        messenger:
#            transports:
#                # replace with your transport name here (e.g., my_transport: 'in-memory://')
#                # For more Messenger testing tools, see https://github.com/zenstruck/messenger-test
#                async: 'in-memory://'
