framework:
    messenger:
        # reset services after consuming messages
        reset_on_message: true
        default_bus: query.bus
        buses:
            query.bus:
                middleware:
                    - validation

            command.bus:
                middleware:
                    - validation

        transports:

        routing:
