
# AUCTIONS
auctions_get_all:
    path: /auctions
    controller: App\UI\Controller\Auctions\GetAuctionsController
    methods: GET

auctions_get:
    path: /auctions/{id}
    controller: App\UI\Controller\Auctions\GetAuctionByIdController
    methods: GET
    requirements:
        id: '%routing.uuid%'
    
auctions_create:
    path: /auctions
    controller: App\UI\Controller\Auctions\CreateAuctionController
    methods: POST

auctions_update:
    path: /auctions/{id}
    controller: App\UI\Controller\Auctions\UpdateAuctionController
    methods: PUT
    requirements:
        id: '%routing.uuid%'

auctions_close:
    path: /auctions/{id}/close
    controller: App\UI\Controller\Auctions\CloseAuctionController
    methods: PUT
    requirements:
        id: '%routing.uuid%'

# BIDS
auction_bid_create:
    path: /bid
    controller: App\UI\Controller\Auctions\CreateBidController
    methods: POST

# USERS
user_signup:
    path: /users
    controller: App\UI\Controller\Users\SignUpController
    methods: POST

user_auth:
    path: /auth
    controller: App\UI\Controller\Users\AuthController
    methods: POST
